import guides from '../content/guides.json';
export default function Home() {const schema={'@context':'https://schema.org','@type':'SoftwareApplication',name:'Tabosmart',applicationCategory:'BrowserApplication',operatingSystem:'Desktop Chrome',softwareVersion:'0.3.0',description:'Local tab organization with reviewed grouping, repeated URL review, saved links and optional on-device AI.',url:'https://tabosm.art',author:{'@type':'Person',name:'Saulius Petreikis'}};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
<header className="site-header"><a className="brand" href="/"><img src="/favicon.svg" width="42" height="42" alt=""/>Tabosmart<span>.</span></a><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#local-ai">Local AI</a><a href="#community">Help shape it ↗</a></nav></header>
<main><section className="hero"><div className="hero-copy"><p className="eyebrow">FOR YOUR MANY OPEN POSSIBILITIES</p><h1>Less tab clutter.<br/><em>More headspace.</em></h1><p className="lead">You didn’t open all those tabs for no reason. Bring related work together. Give the rest a place for later.</p><div className="actions"><a className="cta" href="https://chromewebstore.google.com/detail/tabosmart/kkbfgjpokdhhfgjfeobjjjffmjofhkhf">Chrome Web Store <span>↗</span></a><a className="text-link" href="#community">Help shape what’s next ↗</a></div><p className="micro">Chrome extension · Local processing · You approve every action</p></div><div className="hero-aside"><p className="margin-note">For the things you’re doing.<br/>And the things you might.</p><span className="release-note">0.3.0 · BUILT WITH YOUR FEEDBACK</span></div></section>
<section className="product-proof" id="how-it-works"><div className="proof-top"><span>YOUR NEXT SMALL RESET</span><span>Actual interface · Example browsing data</span></div><img src="/workspace.png" width="1280" height="800" alt="Tabosmart shows related tabs, repeat copies to review, and an invitation to share feedback."/><div className="proof-caption"><strong>A few good decisions. A little more room.</strong><span>Group, save or close only what you choose.</span></div></section>
<section className="benefits"><p className="eyebrow">A LIGHTER BROWSER, ONE CHOICE AT A TIME</p><h2>Your tabs are possibilities.<br/>Give each one a place.</h2><div className="benefit-grid"><article><span className="step-number">01</span><h3>Bring related work together.</h3><p>Review suggested groups and the reason behind each one. Change the name, select the tabs, and make it yours.</p></article><article><span className="step-number">02</span><h3>Give repeat pages a second look.</h3><p>Spot repeated URLs. Check what’s inside before closing selected copies. The same address can hold different unsaved work.</p></article><article><span className="step-number">03</span><h3>Keep the possibility for later.</h3><p>Save URLs on a local shelf. Reopen them when the moment is right. Saving leaves the original tabs open until you choose to close them.</p></article></div></section>
<section className="ai-section" id="local-ai"><div><p className="eyebrow">AN OPTIONAL EXTRA PAIR OF EYES</p><h2>A little AI.<br/>A lot of privacy.</h2></div><div><p>On supported Chrome devices, local AI can propose more connections between tabs, useful group names and clearer wording. <strong>The core works without it.</strong></p><p>Model input is processed on your device, with no cloud fallback. Chrome may need an initial model download. Availability depends on your browser, device and language.</p><p>Tabosmart analyzes open-tab metadata, activity and available browsing history locally. It does not read page content or upload your browsing records.</p><a className="text-link" href="/guides/local-ai-tab-organizer/">What local AI does and doesn’t do ↗</a></div></section>
<section className="film-section" id="film"><div><p className="eyebrow">THE INTENTION, IN HALF A MINUTE</p><h2>Make room.<br/>Keep the possibility.</h2><p>A short introduction from the maker of Tabosmart.</p></div><div><video controls playsInline preload="metadata" poster="/video-poster.png" width="1920" height="1080"><source src="/tabosmart-introduction.mp4" type="video/mp4"/><track default kind="captions" src="/tabosmart-captions.vtt" srcLang="en" label="English"/></video><p className="micro">Actual interface with example browsing data. Synthetic narration using the creator’s own voice reference.</p><details><summary>Read the video transcript</summary><p>You didn't open all those tabs for no reason. You just don't need them all right now. Bring related work together. Review repeat pages. Save links for later. Close only what you choose. Recovery reopens URLs, not unsaved edits. Your browsing data stays on your device. Optional local AI adds suggestions and group names on supported Chrome devices. The core works without it. I'm building this with the people using it. Tell me what missed the point, or what would make it useful tomorrow. Less tab clutter. More headspace.</p></details></div></section>
<section className="community" id="community"><p className="eyebrow">SMALL TOOL. OPEN CONVERSATION.</p><h2>Your browser.<br/>Your next good idea.</h2><p>Tabosmart 0.3.0 is our first feedback release. Your feedback will help shape the path to 1.0.0. Tell us what felt useful, what missed the point, and what would make you use it tomorrow.</p><a className="cta" href="https://tabosmart.featurebase.app/">Share your experience ↗</a><div className="feedback-qr"><a href="https://tabosmart.featurebase.app/" aria-label="Open Tabosmart feedback"><img src="/feedback-qr.svg" width="148" height="148" alt="QR code linking to Tabosmart feedback"/></a><p>Or scan to share<br/>a thought from your phone.</p></div></section>
<section className="guides" id="guides"><p className="eyebrow">A LITTLE LESS TO FIGURE OUT</p><h2>Good questions. Useful answers.</h2><div className="guide-grid">{guides.map(g=><a href={'/guides/'+g.slug+'/'} key={g.slug}><h3>{g.title}</h3><p>{g.description}</p><span>Read the guide ↗</span></a>)}</div></section><section className="faq"><h2>Before you make room.</h2>{[
['What is Tabosmart?','Tabosmart is a Chrome extension that suggests related tab groups, helps review repeated URLs and older work, and stores saved or recoverable URLs locally. You choose what to group, save or close.'],
['Does it close tabs automatically?','No. Nothing moves or closes without your approval. Pinned, audio-playing and protected tabs are excluded from suggestions.'],
['Do I need local AI?','No. Initial suggestions and measured explanations work without AI. Optional assistance is enabled by default for fresh workspaces, but you can switch it off. A required model download starts only through explicit setup.'],
['Does my browsing history leave my device?','Tabosmart does not upload browsing records. It processes available history locally, storing hashed URL identifiers and aggregate visit evidence. Its normal tab views, saved links and Recovery need exact URLs in local storage. Hashes are not anonymous or encrypted.'],
['Can Recovery restore unsaved work?','No. Recovery reopens stored URLs. It cannot restore unsaved edits, form inputs, page state or login sessions. Check important work before closing a page.'],
['Where can I suggest a feature or report a problem?','Use the Help shape Tabosmart link in the extension, or visit our Featurebase portal. Share what you tried, what you expected and what happened. No browsing data is attached automatically. Public posts should not contain private information.'],
['What does version 0.3.0 mean?','This is our first feedback release. Tabosmart already brings related tabs together, helps review repeat pages and saves links for later. Your experiences and ideas will guide improvements on the path to 1.0.0.']
].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
</main><footer><a className="brand" href="/">Tabosmart.</a><p>Made for a browser with room to breathe.</p><a href="/privacy/">Privacy & permissions</a><a href="mailto:saulius.developer@gmail.com">Contact</a></footer></>}
