import sharp from 'sharp';import fs from 'node:fs/promises';import path from 'node:path';
const r=path.resolve(import.meta.dirname,'..'),base=path.join(r,'marketing/community-launch'),raw=path.join(base,'raw'),out=path.join(base,'video/frames');await fs.mkdir(out,{recursive:true});
const logo='data:image/svg+xml;base64,'+(await fs.readFile(path.join(r,'marketing/brand/mark.svg'))).toString('base64');const esc=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const scenes=[
{title:['So many tabs.','So many plans.'],text:['Make room for today’s work.'],kicker:'KEEP THE INTENTION',image:'suggestions-detail.png',bg:'#deef94'},
{title:['Bring work','together.'],text:['Review groups. Clear repeat pages.','Give links a place for later.'],kicker:'YOUR NEXT SMALL RESET',image:'02-groups-with-a-reason.png',crop:{left:289,top:66,width:702,height:668},bg:'#f6e4c9'},
{title:['Always','your call.'],text:['Close only what you choose.','Recovery reopens URLs,','not unsaved edits.'],kicker:'A SUGGESTION, NOT A COMMAND',image:'03-duplicates-your-decision.png',crop:{left:289,top:66,width:702,height:668},bg:'#edf1dc'},
{title:['A little AI.','A lot of','privacy.'],text:['On-device model input.','No cloud fallback.','Core suggestions work without AI.'],kicker:'OPTIONAL HELP',image:'local-ai-settings.png',crop:{left:266,top:93,width:977,height:640},bg:'#f0eee5'},
{title:['Built with','your next','good idea.'],text:['What missed the point?','What would make this useful?'],kicker:'HELP SHAPE TABOSMART',image:'community-feedback.png',crop:{left:266,top:107,width:977,height:653},bg:'#deef94'}
];
for(let i=0;i<scenes.length;i++){const s=scenes[i];let im=sharp(path.join(raw,s.image));if(s.crop)im=im.extract(s.crop);let b=await im.resize({width:1160,height:740,fit:'inside'}).png().toBuffer();const m=await sharp(b).metadata();let svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080"><rect width="1920" height="1080" fill="#faf8f1"/><rect width="620" height="1080" fill="${s.bg}"/><image href="${logo}" x="55" y="43" width="72" height="72"/><g font-family="Arial,Helvetica,sans-serif" fill="#183c35"><text x="139" y="95" font-size="39" font-weight="700" letter-spacing="-1.4">Tabosmart.</text><text x="72" y="231" font-size="15" font-weight="700" letter-spacing="2">${s.kicker}</text>${s.title.map((t,j)=>`<text x="68" y="${332+j*82}" font-size="73" font-weight="700" letter-spacing="-3">${esc(t)}</text>`).join('')}${s.text.map((t,j)=>`<text x="73" y="${365+s.title.length*82+j*40}" font-size="25" fill="#4c6251">${esc(t)}</text>`).join('')}<text x="679" y="115" font-size="17" letter-spacing="1.4" font-weight="700">${i===4?'TABOSMART.FEATUREBASE.APP':i===3?'AVAILABILITY VARIES BY CHROME DEVICE AND LANGUAGE':'ACTUAL INTERFACE · EXAMPLE BROWSING DATA'}</text><rect x="656" y="155" width="1216" height="794" rx="25" fill="white" stroke="#d8ddcf"/></g></svg>`;await sharp(Buffer.from(svg)).composite([{input:b,left:684+Math.floor((1160-m.width)/2),top:182+Math.floor((740-m.height)/2)}]).removeAlpha().png().toFile(path.join(out,`scene-${i}.png`));}
const qrURL='data:image/svg+xml;base64,'+(await fs.readFile(path.join(base,'feedback/feedback-qr.svg'))).toString('base64');
const end=`<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080"><rect width="1920" height="1080" fill="#deef94"/><image href="${logo}" x="859" y="110" width="202" height="202"/><g font-family="Arial,Helvetica,sans-serif" fill="#183c35" text-anchor="middle"><text x="960" y="364" font-size="43" font-weight="700">Tabosmart.</text><text x="960" y="510" font-size="102" font-weight="700" letter-spacing="-4">Less tab clutter.</text><text x="960" y="625" font-size="102" font-weight="700" letter-spacing="-4">More headspace.</text><text x="960" y="730" font-size="31">Help shape what comes next.</text><rect x="570" y="781" width="780" height="80" rx="14" fill="#164e40"/><text x="960" y="834" font-size="33" font-weight="700" fill="white">tabosmart.featurebase.app</text></g><image href="${qrURL}" x="1520" y="690" width="260" height="260"/><text x="1650" y="983" text-anchor="middle" font-family="Arial,sans-serif" font-size="23" fill="#183c35">Scan to share feedback</text></svg>`;await sharp(Buffer.from(end)).removeAlpha().png().toFile(path.join(out,'scene-5.png'));await sharp(path.join(out,'scene-0.png')).resize(1280,720).png().toFile(path.join(base,'video/video-poster.png'));
console.log('Six 1080p story frames rendered.');
